name: Deploy Streamlit App

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Install requirements
        run: pip install hopsworks[python] pandas streamlit plotly altair

      - name: Deploy to Streamlit Sharing
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          streamlit run app.py --server.port=8501
