name: Deploy Streamlit App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install hopsworks[python] pandas streamlit plotly altair

      - name: Deploy to Streamlit Sharing
        run: |
          streamlit run app.py --server.port=8501
