name: Run Feature and Inference Pipeline Daily

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Run Feature Pipeline
        run: uv run python -m src.feature_pipeline

      - name: Run Inference Pipeline
        run: uv run python -m src.inference_pipeline