name: Run Feature and Inference Pipeline Daily

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Run Feature Pipeline
        run: uv run python -m src.feature_pipeline

      - name: Run Inference Pipeline
        run: uv run python -m src.inference_pipeline

      - name: Commit updated feature store
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add amzn_stock_repo/data/

          git diff --cached --quiet || \
            git commit -m "Update feature store"

          git push
