name: Reboot Streamlit Deployment

on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  reboot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create or update dummy file
        run: |
          echo "Dummy file to trigger reboot - $(date)" > dummy_file.txt
      - name: Commit, clean up, and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dummy_file.txt
          git diff --staged --quiet || git commit -m "Trigger reboot and cleanup: $(date)"
          git rm dummy_file.txt
          git commit --amend --no-edit
          git push origin main